pipeline {
  agent {
    dockerfile {
      // label 'k8s' -- where to run the image.
      additionalBuildArgs "--build-arg USER=tester"
      filename 'CorDapp/.ci/Dockerfile'
    }
  }

  options {
      timestamps()
      timeout(time: 1, unit: 'HOURS')
  }

  stages {
    stage('Compile') {
        steps {
            sh "cd CorDapp && ./gradlew --no-daemon -Pcompilation.allWarningsAsErrors=true -Ptests.failFast=false -Ptests.ignoreFailures=true clean assemble"
        }
    }
  }

  post {
    cleanup {
      deleteDir()
    }
  }
}
